name: Verify plugin
on:
  push:
  pull_request:
  schedule:
    - cron: '23 7 * * 1'
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
      - name: Compile and test
        run: bash ./gradlew test --console=plain
      - name: Retain test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/
